version: '2'

networks:
  backend:

volumes:
  db:

services:
  db:
    image: mysql
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/logs:/var/log/mysql/
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d
    command: --sql_mode=""
    ports:
      - "${MYSQL_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '7.4'
        DOCKER_PHP_XDEBUG_VERSION: ${DOCKER_PHP_XDEBUG_VERSION}
        TZ: ${WORKSPACE_TIMEZONE}
        PHP_IDE_CONFIG: serverName=phpxdebug
    working_dir: /var/www/crm
    volumes:
      - .:/var/www/crm
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${PHP_PORT}:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/crm
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    ports:
      - "${NGINX_PORT}:80"
    networks:
      backend:
    depends_on:
      - php
      - db